// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToMd(arg1) {
  return window['go']['main']['App']['ConvertToMd'](arg1);
}

export function SelectAndReadFile() {
  return window['go']['main']['App']['SelectAndReadFile']();
}
