// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertToMd(arg1:main.FileDetails):Promise<main.ReturnResult>;

export function SelectAndReadFile():Promise<main.FileDetails>;
