// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertToMd(arg1:main.FileDetails):Promise<main.ReturnResult>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetStartupFile():Promise<main.ReturnResult>;

export function LoadFileFromPath(arg1:string):Promise<main.ReturnResult>;

export function OpenFileFromFrontend(arg1:main.FileDetails):Promise<main.ReturnResult>;

export function SelectAndReadFile():Promise<main.FileDetails>;
